[project]
name = "bibliometrics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jinja2>=3.1.4",
    "jupyterlab>=4.3.1",
    "pandas>=2.2.3",
    "pybliometrics>=4.1",
]
